/**
 * QA round-2 red tests — import/export fidelity & converters (Task 5-c, agent qa-red-interop).
 *
 * Pins the documented-but-broken interop behaviors recorded in the round-2 blackbox QA reports:
 *   - QA-08 E9 / QA-05 F4+F5 — Obsidian import silently drops content around code fences (§27)
 *   - QA-08 E7 / QA-05 F2-residual — embed refs `![[x]]` lack `.md` ⇒ guaranteed broken refs (§27/§31)
 *   - QA-08 E11 — multi-word Logseq property leaves a truncated garbage node (§31)
 *   - QA-09 D12 / QA-05 F9 — `--merge-strategy ask` reports nothing on the export→edit→import
 *     flow (§27 "report conflicts, don't merge"; §35 conflicts[] shape)
 *   - QA-05 F15 / QA-10 #9 — `export --from /nonexistent` is success-shaped nothing (§37/§19)
 *   - QA-05 F18 — active `_adr/` not exported although §28 excludes only `_adr/_archive/` (§28)
 *   - QA-05 F16 / QA-09 D9 — OPML round-trip kills `see:` refs (`→` stays literal) (§28/§45)
 *   - QA-09 D5 — Obsidian round-trip destroys owner/gate state (emoji literals) (§3/§28/§30)
 *
 * Every non-control test asserts the DOCUMENTED contract and MUST fail (red) at the current
 * HEAD for the documented reason. No .skip, no swallowing, no assertion encodes buggy behavior.
 * Clearly-marked controls (expected PASS) isolate the failing scenario from working machinery.
 *
 * Method: blackbox CLI spawn (Bun.spawnSync), scratch workspaces under repo
 * .tmp/qa-round2/interop-fidelity (gitignored), afterEach cleanup. Round-trip inputs are
 * generated by the CLI itself (`export` first) so the tests pin real encodings, never guesses.
 */
import { describe, expect, test, afterEach } from 'bun:test';
import { join, dirname, relative } from 'path';
import {
  mkdirSync, rmSync, readFileSync, writeFileSync, existsSync, readdirSync, statSync,
} from 'fs';

const REPO = join(import.meta.dir, '..', '..');
const CLI = join(REPO, 'src', 'cli.ts');
const FLAT_PROJECT = join(REPO, 'test', 'fixtures', 'flat-project');
const IMPORT_FIXTURES = join(REPO, 'test', 'fixtures', 'import-fixtures');
const BASE = join(REPO, '.tmp', 'qa-round2', 'interop-fidelity');

function runCli(args: string[], cwd: string): { exit: number | null; out: string; err: string } {
  const env = { ...process.env, CANS_ROOT: '' } as Record<string, string>; // isolation: scratch cwd decides the workspace
  const p = Bun.spawnSync(['bun', 'run', CLI, ...args], { cwd, env, stdout: 'pipe', stderr: 'pipe' });
  return { exit: p.exitCode, out: p.stdout.toString(), err: p.stderr.toString() };
}

/** Fresh `cans init` workspace under BASE/<name>; `bare` keeps it to 00-overview + _rules.yaml. */
function makeWorkspace(name: string, bare = true): string {
  const dir = join(BASE, name);
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  const r = runCli(['init', ...(bare ? ['--bare'] : [])], dir);
  if (r.exit !== 0) throw new Error(`setup: cans init failed in ${dir}: ${r.out}${r.err}`);
  return dir;
}

/** Write a file inside the scratch workspace (dirs created as needed). */
function putFile(ws: string, rel: string, content: string): void {
  const p = join(ws, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content);
}

/** Concatenation of every file under root (recursive) — overflow files included. */
function readAllUnder(root: string): string {
  const out: string[] = [];
  const walk = (d: string): void => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.isFile()) out.push(readFileSync(p, 'utf-8'));
    }
  };
  if (existsSync(root)) walk(root);
  return out.join('\n');
}

/** First file under root whose basename equals `name` (searches subdirs, e.g. _tasks/). */
function findFileNamed(root: string, name: string): string | null {
  const walk = (d: string): string | null => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, e.name);
      if (e.isDirectory()) {
        const hit = walk(p);
        if (hit) return hit;
      } else if (e.isFile() && e.name === name) return p;
    }
    return null;
  };
  return existsSync(root) ? walk(root) : null;
}

/** First file in `dir` whose content contains `needle`. */
function findFileContaining(dir: string, needle: string): string | null {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isFile() && readFileSync(p, 'utf-8').includes(needle)) return p;
  }
  return null;
}

afterEach(() => {
  rmSync(BASE, { recursive: true, force: true });
});

describe('QA round-2 interop fidelity (QA-05 F4/F5/F9/F15/F16/F18, QA-08 E7/E9/E11, QA-09 D5/D9/D12, QA-10 #9)', () => {
  // ── 1. QA-08 E9 / QA-05 F4+F5 (MAJOR data loss, §27/§31) ────────────────────────────────
  test('QA-08 E9 / QA-05 F4+F5 (§27, §31): obsidian import with a code fence in the flow must not silently drop ANY non-empty input line — fenced lines extracted, post-fence bullet and callouts preserved', () => {
    const ws = makeWorkspace('e9-fence-flow');
    const input = [
      '- Parent topic',
      '  - ```python',
      '    auth_token = "ZQCODE1 alpha"',
      '    refresh_token = "ZQCODE2 beta"',
      '    ```',
      '- normal child',
      '> [!warning] ZQWARN rate limits apply',
      '> ZQBODY back off before retry',
      '',
    ].join('\n');
    putFile(ws, 'fix/e9-obsidian.md', input);
    const r = runCli(['import', 'obsidian', 'fix/e9-obsidian.md', '--json'], ws);
    expect(r.exit).toBe(0); // §27: import proceeds; "Let cans check report issues after"

    // §27 import rules: "Preserve hierarchy", "Extract code blocks → overflow files" — nothing
    // may vanish silently. Mechanism-agnostic survival check: every non-empty input line's
    // content must exist somewhere under cans/ (imported spec file OR overflow file).
    // Only the two fence-marker lines (```python / ```) are exempt: extraction legitimately
    // replaces the fence SYNTAX itself; their content is the two ZQCODE lines below.
    const all = readAllUnder(join(ws, 'cans'));
    const mustSurvive: Array<[string, string]> = [
      ['- Parent topic', 'Parent topic'],
      ['    auth_token = "ZQCODE1 alpha"', 'ZQCODE1'],
      ['    refresh_token = "ZQCODE2 beta"', 'ZQCODE2'],
      ['- normal child', 'normal child'],
      ['> [!warning] ZQWARN rate limits apply', 'ZQWARN'],
      ['> ZQBODY back off before retry', 'ZQBODY'],
    ];
    for (const [line, token] of mustSurvive) {
      expect(all, `input line silently lost: "${line}"`).toContain(token);
    }

    // The real bullet AFTER the closing fence must exist as a parsed node (`- normal child`),
    // not as prose buried in some other line.
    const nodeLine = all.split('\n').find(l => /^-\s+normal child$/.test(l.trim()));
    expect(nodeLine, '`- normal child` must survive as a parsed node').toBeDefined();

    // Obsidian callout content (`> [!warning]` block) must be handled (§31), not dropped.
    expect(all).toContain('ZQWARN');
    expect(all).toContain('ZQBODY');
  });

  // ── 2. QA-08 E7 / QA-05 F2-residual (MINOR, §27/§31) ────────────────────────────────────
  test('QA-08 E7 (§27, §31, §12): obsidian embed `![[some-embed]]` must import as `see: some-embed.md` (with .md, same treatment as wiki-links) — a resolvable ref, 0 broken', () => {
    const ws = makeWorkspace('e7-embed-md');
    // Seed the embed target so the ref CAN resolve if generated in the canonical form.
    putFile(ws, join('cans', 'some-embed.md'), '- Embedded note target\n');
    putFile(ws, 'fix/embed.md', '- Parent topic\n  - ![[some-embed]]\n');
    const r = runCli(['import', 'obsidian', 'fix/embed.md', '--json'], ws);
    expect(r.exit).toBe(0);
    expect(r.out).toContain('07-parent-topic.md'); // import happened
    const content = readFileSync(join(ws, 'cans', '07-parent-topic.md'), 'utf-8');
    // §27/§31: `![[embeds]]` convert to `see:` — with the canonical .md suffix exactly like
    // wiki-links do (QA-08 E6 shows `[[x#y]]` → `see: x.md#y`). Current: bare `see: some-embed`
    // ⇒ guaranteed broken ref (§12: file not found = broken ref ERROR).
    expect(content).toContain('see: some-embed.md');
    expect(content).not.toMatch(/see:\s+some-embed(?!\.md)/);
    // With cans/some-embed.md present, the converted ref must resolve — 0 broken refs.
    const chk = runCli(['check', '--json'], ws);
    const cj = JSON.parse(chk.out);
    expect(cj.refs.broken).toBe(0);
  });

  // ── 3. QA-08 E11 (MINOR, §31) ───────────────────────────────────────────────────────────
  test('QA-08 E11 (§31): logseq multi-word `key:: value` property must be fully stripped — no truncated garbage node `- multi word`', () => {
    const ws = makeWorkspace('e11-multword-prop');
    putFile(ws, 'fix/logseq-props.md', [
      '- Topic ZQTOPIC',
      '  - multi word prop:: has spaces and stuff',
      '  - after props ZQAFTER',
      '',
    ].join('\n'));
    const r = runCli(['import', 'logseq', 'fix/logseq-props.md', '--json'], ws);
    expect(r.exit).toBe(0);
    const all = readAllUnder(join(ws, 'cans'));
    // Sanity: the import parsed the surrounding lines (single-word keys strip cleanly — QA-08 E10).
    expect(all).toContain('ZQTOPIC');
    expect(all).toContain('ZQAFTER');
    // §31 stripMetadata: "removes Logseq `::` properties" — a multi-word key is still a
    // property line. Current: leftover node `- multi word` (partial strip).
    expect(all).not.toContain('multi word');
    expect(all).not.toMatch(/prop::/); // the metadata marker itself must not survive either
    // Fully stripped = key AND value gone (same contract as the clean single-word case, E10).
    expect(all).not.toContain('has spaces and stuff');
  });

  // ── 4. QA-09 D12 / QA-05 F9 (MAJOR, §27/§35) ────────────────────────────────────────────
  test('QA-09 D12 / QA-05 F9 (§27, §35): re-importing an edited export over the workspace that still holds the original — `--merge-strategy ask` must REPORT the conflict (conflicts[] populated per §35) and must not merge', () => {
    const ws = makeWorkspace('d12-ask-edited-export');
    // Workspace holding the original: 02-authentication.md with the cans version of the node.
    putFile(ws, join('cans', '02-authentication.md'), '- Sessions\n  - Expire after 24 hours\n');
    const ex = runCli(['export', 'opml', '--json'], ws);
    expect(ex.exit).toBe(0);
    const expDir = join(ws, 'cans-export', 'opml');
    const expFile = findFileContaining(expDir, 'Expire after 24 hours');
    expect(expFile, 'setup: exported OPML containing the node must exist').not.toBeNull();
    // Hand-edit the EXPORTED source: 24 → 72 hours (the human/external change).
    writeFileSync(expFile!, readFileSync(expFile!, 'utf-8').replace(/24 hours/g, '72 hours'));
    // Re-import the edited export over the workspace with ask.
    const src = relative(ws, expFile!);
    const r = runCli(['import', 'opml', src, '--merge-strategy', 'ask', '--json'], ws);
    expect(r.exit).toBe(0);
    const j = JSON.parse(r.out);
    // §27: ask = "report conflicts, don't merge". The workspace still holds "Expire after
    // 24 hours" while the import brings "Expire after 72 hours" — a machine consumer MUST be
    // able to learn that a conflict happened. Current: conflicts:[] + a silently forked file.
    expect(Array.isArray(j.conflicts)).toBe(true);
    expect(j.conflicts.length, 'ask must report the conflict (§27/§35)').toBeGreaterThan(0);
    // §35 conflicts[] entry shape: { file, line, cansVersion, importVersion, resolution }.
    const c = j.conflicts[0];
    expect(typeof c.file).toBe('string');
    expect((c.file as string).length).toBeGreaterThan(0);
    expect(typeof c.line).toBe('number');
    expect(c.cansVersion).toContain('24 hours'); // cans version = the workspace's text
    expect(c.importVersion).toContain('72 hours'); // import version = the edited export
    expect(typeof c.resolution === 'string' && (c.resolution as string).length > 0).toBe(true);
    // Don't merge honored: the CANS file named by the report still holds the cans version,
    // and the import version was not written into it.
    const cansFile = join(ws, 'cans', c.file);
    expect(existsSync(cansFile)).toBe(true);
    const content = readFileSync(cansFile, 'utf-8');
    expect(content).toContain('Expire after 24 hours');
    expect(content).not.toContain('72 hours');
  });

  // ── 5. CONTROL (expected PASS) — isolates finding 4 to the export→edit→import flow ──────
  test('control (expected PASS, §27/§35): `--merge-strategy ask` DOES report conflicts on a direct same-target re-import (QA-05 F9 scenario) — proving the ask machinery itself can report', () => {
    const ws = makeWorkspace('control-ask-same-target');
    putFile(ws, 'dynalist-export.opml', readFileSync(join(IMPORT_FIXTURES, 'dynalist-export.opml'), 'utf-8'));
    const first = runCli(['import', 'opml', 'dynalist-export.opml'], ws);
    expect(first.exit).toBe(0);
    const f = join(ws, 'cans', '07-authentication.md');
    writeFileSync(f, readFileSync(f, 'utf-8').replace('Expire after 24 hours', 'Expire after 48 hours'));
    const r = runCli(['import', 'opml', 'dynalist-export.opml', '--merge-strategy', 'ask', '--json'], ws);
    expect(r.exit).toBe(0);
    const j = JSON.parse(r.out);
    expect(j.conflicts.length).toBeGreaterThan(0);
    expect(j.conflicts[0].resolution).toBe('ask');
    expect(j.conflicts[0].file).toBe('07-authentication.md');
    // Don't merge: human version kept in place.
    const after = readFileSync(f, 'utf-8');
    expect(after).toContain('Expire after 48 hours');
    expect(after).not.toContain('Expire after 24 hours');
  });

  // ── 6. QA-05 F15 / QA-10 #9 (MINOR, §37/§19) ────────────────────────────────────────────
  test('QA-05 F15 / QA-10 #9 (§37, §19): `export opml --from /nonexistent` must be a user-correctable error (exit 1 + ✗ what/fix, JSON error field) — never success-shaped nothing (ok:true, filesExported 0, exit 0)', () => {
    const ws = makeWorkspace('f15-from-nonexistent');
    const r = runCli(['export', 'opml', '--from', '/nonexistent-dir-xyz-qa', '--json'], ws);
    // §37: a nonexistent source dir is user-correctable → exit 1 with a stated reason.
    expect(r.exit).toBe(1); // current: 0
    const j = JSON.parse(r.out);
    expect(j.ok).toBe(false); // current: true
    expect(typeof j.error === 'string' && (j.error as string).length > 0).toBe(true); // §37 reason for machine consumers
    // Human surface must carry the ✗ what/fix pattern (§37), not "Exported opml → … (0 files)".
    const rh = runCli(['export', 'opml', '--from', '/nonexistent-dir-xyz-qa'], ws);
    expect(rh.exit).toBe(1);
    expect(`${rh.out}${rh.err}`).toMatch(/✗/);
    expect(`${rh.out}${rh.err}`).not.toMatch(/Exported opml →/);
  });

  // ── 7. QA-05 F18 (MINOR, §28) ───────────────────────────────────────────────────────────
  test('QA-05 F18 (§28): active `_adr/` records must be exported — §28 excludes only `_adr/_archive/`, `_collab/`, `_rules.yaml`, `AGENTS.md`', () => {
    const ws = makeWorkspace('f18-adr-export', false); // full init: 00–06 skeleton present
    const nr = runCli(['new', 'adr', 'Test Export Adr'], ws);
    expect(nr.exit).toBe(0);
    const adrFiles = readdirSync(join(ws, 'cans', '_adr')).filter(f => f.endsWith('.md'));
    expect(adrFiles.some(f => /test-export-adr/.test(f)), 'setup: ADR created').toBe(true);
    const ex = runCli(['export', 'opml', '--json'], ws);
    expect(ex.exit).toBe(0);
    // §28: excluding `_adr/_archive/` implies active `_adr/` IS exported. Current: the ADR is
    // silently missing from cans-export/opml/ (all `_`-prefixed dirs dropped per §32 discovery).
    const listing = readdirSync(join(ws, 'cans-export', 'opml'));
    expect(
      listing.some(f => /test-export-adr/.test(f)),
      `exported set must contain an artifact for the active ADR; got: ${listing.join(', ')}`,
    ).toBe(true);
  });

  // ── 8. QA-05 F16 / QA-09 D9 (§28/§45) ───────────────────────────────────────────────────
  test('QA-05 F16 / QA-09 D9 (§28, §45): OPML round-trip must restore `see: 02-authentication.md#Sessions` from the exported `→ 02-authentication.md#Sessions` marker — refs survive, 0 broken', () => {
    // Source workspace: flat-project 02 (canonical home) + 04 (holds the see: ref).
    const src = makeWorkspace('f16-rt-src');
    for (const f of ['02-authentication.md', '04-api.md']) {
      putFile(src, join('cans', f), readFileSync(join(FLAT_PROJECT, f), 'utf-8'));
    }
    const ex = runCli(['export', 'opml', '--json'], src);
    expect(ex.exit).toBe(0);
    // §28 table: CANS `see: X.md#Y` → OPML `→ X.md#Y` (green precondition — pins the real encoding).
    const exp04 = findFileContaining(join(src, 'cans-export', 'opml'), '→ 02-authentication.md#Sessions');
    expect(exp04, 'exported OPML must encode the ref as `→ 02-authentication.md#Sessions`').not.toBeNull();
    // Round-trip: fresh workspace (with the ref target seeded so a restored ref resolves), import.
    const rt = makeWorkspace('f16-rt-import');
    putFile(rt, join('cans', '02-authentication.md'), readFileSync(join(FLAT_PROJECT, '02-authentication.md'), 'utf-8'));
    const r = runCli(['import', 'opml', relative(rt, exp04!), '--json'], rt);
    expect(r.exit).toBe(0);
    const j = JSON.parse(r.out);
    expect(j.newFiles.length).toBeGreaterThan(0);
    const imported = readFileSync(join(rt, 'cans', j.newFiles[0]), 'utf-8');
    // §28 table inverse: importing the OPML must restore the CANS ref form `see: X.md#Y`.
    // Current: the literal arrow text stays as node prose — refs die (0 see: refs).
    expect(imported).toMatch(/see:?\s+02-authentication\.md#Sessions/);
    expect(imported).not.toContain('→ 02-authentication.md#Sessions');
    // §45 "OPML roundtrips pass": the restored ref must be counted AND resolve (target seeded).
    const chk = runCli(['check', '--json'], rt);
    const cj = JSON.parse(chk.out);
    expect(cj.refs.total).toBeGreaterThanOrEqual(1); // current: 0 — the ref no longer exists
    expect(cj.refs.broken).toBe(0);
  });

  // ── 9. QA-09 D5 (MAJOR, §3/§28/§30) ─────────────────────────────────────────────────────
  test('QA-09 D5 (§3, §28, §30): obsidian round-trip must restore owner arrows and the human gate (`← agent-1`, `← @human`) — no literal emoji state; status must see gates again after re-import', () => {
    // Source workspace: task file with real owner/gate state (§3/§30 — the file IS the state).
    const src = makeWorkspace('d5-rt-src');
    putFile(src, join('cans', '_tasks', 'rt-owner-gate.md'), [
      '# rt-owner-gate',
      '- Tasks',
      '  - [ ] Do thing ← agent-1',
      '  - [x] Approved ← @human',
      '',
    ].join('\n'));
    // Green precondition: owners/gates are real state that status sees BEFORE the round-trip.
    const st0 = JSON.parse(runCli(['status', '--json'], src).out);
    const before = st0.taskFiles.find((t: { name: string }) => t.name === 'rt-owner-gate');
    expect(before).toBeDefined();
    expect(before.gatesTotal).toBeGreaterThanOrEqual(1);
    expect(Object.keys(st0.owners)).toContain('agent-1');
    // §28 export table (green precondition): `← agent-1` → `🤖 agent-1`, `← @human` → `⏳ Human`.
    const ex = runCli(['export', 'obsidian', '--include-tasks', '--json'], src);
    expect(ex.exit).toBe(0);
    const expDir = join(src, 'cans-export', 'obsidian');
    const expTask = readdirSync(expDir).map(f => join(expDir, f)).find(p => /rt-owner-gate/.test(p));
    expect(expTask, 'setup: exported obsidian task file must exist').toBeDefined();
    const expContent = readFileSync(expTask!, 'utf-8');
    expect(expContent).toContain('🤖 agent-1');
    expect(expContent).toContain('⏳ Human');
    // Round-trip: import the exported file back (into _tasks so status can evaluate it — §20
    // documents `import [--out <path>]`). Import must reverse-map the §28 table.
    const rt = makeWorkspace('d5-rt-import');
    const r = runCli(['import', 'obsidian', relative(rt, expTask!), '--out', join('cans', '_tasks'), '--json'], rt);
    expect(r.exit).toBe(0);
    const j = JSON.parse(r.out);
    expect(j.newFiles.length).toBeGreaterThan(0);
    const importedPath = findFileNamed(join(rt, 'cans'), j.newFiles[0]);
    expect(importedPath, 're-imported task file must exist under cans/').not.toBeNull();
    const imported = readFileSync(importedPath!, 'utf-8');
    // Owner arrow + human gate must be restored as CANS owner/gate syntax — NOT emoji literals.
    expect(imported).toContain('← agent-1');
    expect(imported).toContain('← @human');
    expect(imported).not.toContain('🤖');
    expect(imported).not.toContain('⏳');
    // §3/§30: owners/gates are real state — status must see them after the round-trip.
    const st1 = JSON.parse(runCli(['status', '--json'], rt).out);
    const entry = st1.taskFiles.find((t: { name: string }) => t.name === j.newFiles[0].replace(/\.md$/, ''));
    expect(entry, `status must list the re-imported task file ${j.newFiles[0]}`).toBeDefined();
    expect(entry.gatesTotal, 'human gate lost by the round-trip (QA-09 D5)').toBeGreaterThanOrEqual(1);
    expect(Object.keys(st1.owners), 'owner state lost by the round-trip (QA-09 D5)').toContain('agent-1');
  });
});
